[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "4.5.1"
cargo-watch = "8.4.1"
rand = "0.8.5"
reqwest = "0.11.23"
rocket = "0.5.0"
